### ISSUE TITLE
How are docker images pushed?

### ISSUE THREAD

**Issue by carlpett** [docker/distribution-library-image#77]
_Moved from https://github.com/docker/distribution/issues/2655_

Somewhat related to https://github.com/docker/distribution/issues/2623 and https://github.com/docker/distribution/issues/2641, I was looking at the images on the Docker hub: https://hub.docker.com/r/library/registry/tags/
No release has been made on Github since 20 Jul 2017, yet the images are only 25 days old. The Circle CI definitions do not seem to do any push on release, so I assume this is done manually? Could we get some details on what has changed on 2.6.2 and 2.5.2 between their Github releases and the images that were pushed on 6 Jul 2018?

There's been a number of credential hijacks recently, which makes this a bit worrying.

Pinging some people who seem to possibly be able to answer this: @stevvooe @dmcgowan

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images for the source of the official images.  The recent push of `registry` was likely due to https://github.com/docker-library/official-images/pull/4501, which lines up perfectly with the timeline described (~25 days ago); `registry` is `FROM alpine:3.4`, so when `alpine:3.4` was updated, the `registry` image was rebuilt.

**Comment by carlpett** [comment]
I see. It seems quite unexpected to me that a semver-tagged image would be updated without version bump because some underlying component changed, though? Doesn't this invite subtle differences over larger installations which use the same tag but different images?

**Comment by tianon** [comment]
We've had a few users who expected that, but the majority usually expect the opposite, namely that security and base OS updates get applied automatically and retroactively (because in the end, the version of the software they're consuming is all they care about not changing).

If you're looking for a fixed, unchanging base, that's the exact use case for the content-addressable digests and pull-by-digest, and why when you deploy a service in Docker Swarm Mode, it'll automatically resolve any image/tag references to an explicit digest (so that it can guarantee that the exact same bits get deployed across the cluster, regardless of the time the bits get deployed or any tag changes since).

The "repo-info" repository (https://github.com/docker-library/repo-info) is a good reference for looking up the appropriate digest values without pulling the images: https://github.com/docker-library/repo-info/blob/63d11ee0217f5defbb729876a1c1b96cf0a92271/repos/registry/remote/latest.md

(And you can walk backwards in time through the commits there to get old digest values, such as https://github.com/docker-library/repo-info/commits/63d11ee0217f5defbb729876a1c1b96cf0a92271/repos/registry/remote/latest.md which leads to https://github.com/docker-library/repo-info/blob/acd463b0dbb4b08e9a421cb926cb368adf914cc5/repos/registry/remote/latest.md.)

**Comment by carlpett** [comment]
Okay, even though it wasn't to my preferences, at least you've obviously thought your approach through :smile: That's the most important.
Nice with the repo-info, had I found that it would have eased my concerns. This might be a point of feedback in general - there's a lot of repos to go though, and to me at least it wasn't obviously discoverable. Perhaps the code repos (such as `distribution` in this case) could have a series of links to the other relevant repos/paths?

**Comment by tianon** [comment]
> to me at least it wasn't obviously discoverable

We've done our best with that, if you look at the "Quick Reference" section at the top of https://hub.docker.com/_/registry/, it has links to a number of interesting/useful places including `repo-info`.

**Comment by carlpett** [comment]
Haha. Right, that's on me. Probably never came back to it after skimming it the first time.
All good, sorry for the noise!
